# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "backend" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-2`.
#    Replace the value of the `ECR_REPOSITORY` environment variable in the workflow below with your repository's name.
#    Replace the value of the `AWS_REGION` environment variable in the workflow below with your repository's region.
#
# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/firstRun
#    Replace the value of the `ECS_SERVICE` environment variable in the workflow below with the name you set for the Amazon ECS service.
#    Replace the value of the `ECS_CLUSTER` environment variable in the workflow below with the name you set for the cluster.
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#    Replace the value of the `ECS_TASK_DEFINITION` environment variable in the workflow below with the path to the JSON file.
#    Replace the value of the `CONTAINER_NAME` environment variable in the workflow below with the name of the container
#    in the `containerDefinitions` section of the task definition.
#
# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Continuous Integration when accure push at main branch

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: with_ance               # set this to your Amazon ECR repository name
  CONTAINER_NAME: with_ance_backend           # set this to the name of the container in the

permissions:
  contents: read

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        ref: ${{ github.event.push.base_ref }}
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        persist-credentials: true

    - name: Set sha outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Check sha outputs
      run: echo ${{ steps.vars.outputs.sha_short }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.BUILDER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.BUILDER_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Create .env file
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: |
        jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS_CONTEXT" > .env

    - name: Build, tag, and push image to Amazon ECR
      id: build-push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        sha: ${{ steps.vars.outputs.sha_short }}
        branch: ${{ github.ref_name }}
        
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to EKS or local k8s.
        echo ${{ github.event.push.base_ref }}
        echo ${{ github.event.push.after }}
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ env.sha }} --build-arg BRANCH=${{ env.branch }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:main-${{ env.sha }}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:main-${{ env.sha }}"

    - uses: mikefarah/yq@master
    - name: create PR on with_ance_config
      id: create-config
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        SHA: ${{ steps.vars.outputs.sha_short }}
        REPOURL: "https://github.com/ysa5347/with_ance_config.git"
        TAG: ${{ env.ECR_REGISTRY }}/$ECR_REPOSITORY:stage-${{ env.SHA }}
        branch: ${{ github.ref_name }}
      run: |
        git clone ${{ env.REPOURL }}
        git config --global user.email "ysa5347@gmail.com"
        git config --global user.name "ysa5347"
        cd with_ance_config
        git checkout main
        yq -i '(.images.tags[]|select(.name==strenv(branch))|.tag)=strenv(TAG)' ./with_ance/values.yaml
        git add .
        git commit -m "TAG; tag $branch"

    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        ssh: true
        repository: "with_ance_config"
        branch: main  